// @generated by protobuf-ts 2.8.2 with parameter output_javascript
// @generated from protobuf file "grpc_api/bilibili/pgc/gateway/player/v2/playurl.proto" (package "bilibili.pgc.gateway.player.v2", syntax proto3)
// tslint:disable
import { PlayURL } from "./playurl";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
/**
 * 视频url
 *
 * @generated from protobuf service bilibili.pgc.gateway.player.v2.PlayURL
 */
export class PlayURLClient {
    constructor(_transport) {
        this._transport = _transport;
        this.typeName = PlayURL.typeName;
        this.methods = PlayURL.methods;
        this.options = PlayURL.options;
    }
    /**
     * 播放页信息
     *
     * @generated from protobuf rpc: PlayView(bilibili.pgc.gateway.player.v2.PlayViewReq) returns (bilibili.pgc.gateway.player.v2.PlayViewReply);
     */
    playView(input, options) {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PlayViewComic(bilibili.pgc.gateway.player.v2.PlayViewReq) returns (bilibili.pgc.gateway.player.v2.PlayViewReply);
     */
    playViewComic(input, options) {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
}
