// @generated by protobuf-ts 2.8.2 with parameter output_javascript
// @generated from protobuf file "grpc_api/bilibili/pgc/gateway/player/v2/playurl.proto" (package "bilibili.pgc.gateway.player.v2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../../../../../google/protobuf/timestamp";
/**
 * 角标信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.BadgeInfo
 */
export interface BadgeInfo {
    /**
     * 角标文案
     *
     * @generated from protobuf field: string text = 1;
     */
    text: string;
    /**
     * 角标色值
     *
     * @generated from protobuf field: string bg_color = 2;
     */
    bgColor: string;
    /**
     * 角标色值-夜间模式
     *
     * @generated from protobuf field: string bg_color_night = 3;
     */
    bgColorNight: string;
    /**
     * 文案色值
     *
     * @generated from protobuf field: string text_color = 4;
     */
    textColor: string;
    /**
     * ? 新版本客户端已弃用此项
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.GradientColor bg_gradient_color = 5;
     */
    bgGradientColor?: GradientColor;
}
/**
 * Dialog组件: 底部显示
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.BottomDisplay
 */
export interface BottomDisplay {
    /**
     * 文案
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo title = 1;
     */
    title?: TextInfo;
    /**
     * 图标
     *
     * @generated from protobuf field: string icon = 2;
     */
    icon: string;
}
/**
 * 按钮信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.ButtonInfo
 */
export interface ButtonInfo {
    /**
     * 按钮文案
     *
     * @generated from protobuf field: string text = 1;
     */
    text: string;
    /**
     * 按钮字体色值
     *
     * @generated from protobuf field: string text_color = 2;
     */
    textColor: string;
    /**
     * 按钮字体色值-夜间模式
     *
     * @generated from protobuf field: string text_color_night = 3;
     */
    textColorNight: string;
    /**
     * 按钮背景色
     *
     * @generated from protobuf field: string bg_color = 4;
     */
    bgColor: string;
    /**
     * 按钮背景色-夜间模式
     *
     * @generated from protobuf field: string bg_color_night = 5;
     */
    bgColorNight: string;
    /**
     * 按钮链接
     *
     * @generated from protobuf field: string link = 6;
     */
    link: string;
    /**
     * 按钮动作类型
     *
     * @generated from protobuf field: string action_type = 7;
     */
    actionType: string;
    /**
     * 角标信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.BadgeInfo badge_info = 8;
     */
    badgeInfo?: BadgeInfo;
    /**
     * 埋点上报信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Report report = 9;
     */
    report?: Report;
    /**
     * 左侧删除线样式文案
     *
     * @generated from protobuf field: string left_strikethrough_text = 10;
     */
    leftStrikethroughText: string;
    /**
     * 缩略按钮文案信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo simple_text_info = 11;
     */
    simpleTextInfo?: TextInfo;
    /**
     * 缩略按钮背景色值
     *
     * @generated from protobuf field: string simple_bg_color = 12;
     */
    simpleBgColor: string;
    /**
     * 缩略按钮字体色值-夜间模式
     *
     * @generated from protobuf field: string simple_bg_color_night = 13;
     */
    simpleBgColorNight: string;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.GradientColor bg_gradient_color = 14;
     */
    bgGradientColor?: GradientColor;
    /**
     * @generated from protobuf field: map<string, string> order_report_params = 15;
     */
    orderReportParams: {
        [key: string]: string;
    };
}
/**
 * 投屏限制. code = 0 时为无限制, 否则表示不不允许投屏并提示message
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.CastTips
 */
export interface CastTips {
    /**
     * @generated from protobuf field: int32 code = 1;
     */
    code: number;
    /**
     *
     *
     * @generated from protobuf field: string message = 2;
     */
    message: string;
}
/**
 * 跳过片头/片尾配置
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.ClipInfo
 */
export interface ClipInfo {
    /**
     * @generated from protobuf field: int64 material_no = 1;
     */
    materialNo: bigint;
    /**
     * DASH分段始
     *
     * @generated from protobuf field: int32 start = 2;
     */
    start: number;
    /**
     * DASH分段终
     *
     * @generated from protobuf field: int32 end = 3;
     */
    end: number;
    /**
     * Clip类型
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ClipType clip_type = 4;
     */
    clipType: ClipType;
    /**
     * 跳过片头/片尾时的提示语
     *
     * @generated from protobuf field: string toast_text = 5;
     */
    toastText: string;
    /**
     *
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.MultiView multi_view = 6;
     */
    multiView?: MultiView;
}
/**
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.ContinuePlayInfo
 */
export interface ContinuePlayInfo {
    /**
     * @generated from protobuf field: int64 continue_play_ep_id = 1;
     */
    continuePlayEpId: bigint;
}
/**
 * 优惠券
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Coupon
 */
export interface Coupon {
    /**
     * 优惠券token
     *
     * @generated from protobuf field: string coupon_token = 1;
     */
    couponToken: string;
    /**
     * 优惠券类型
     * 1:折扣券 2:满减券 3:兑换券
     *
     * @generated from protobuf field: int64 type = 2;
     */
    type: bigint;
    /**
     * 优惠券面值
     *
     * @generated from protobuf field: string value = 3;
     */
    value: string;
    /**
     * 优惠券使用描述
     *
     * @generated from protobuf field: string use_desc = 4;
     */
    useDesc: string;
    /**
     * 优惠券标题
     *
     * @generated from protobuf field: string title = 5;
     */
    title: string;
    /**
     * 优惠券描述
     *
     * @generated from protobuf field: string desc = 6;
     */
    desc: string;
    /**
     * 优惠券支付按钮文案
     *
     * @generated from protobuf field: string pay_button_text = 7;
     */
    payButtonText: string;
    /**
     * 优惠券支付按钮删除线文案
     *
     * @generated from protobuf field: string pay_button_text_line_through = 8;
     */
    payButtonTextLineThrough: string;
    /**
     * 实付金额
     *
     * @generated from protobuf field: string real_amount = 9;
     */
    realAmount: string;
    /**
     * 使用过期时间
     *
     * @generated from protobuf field: google.protobuf.Timestamp expire_time = 10;
     */
    expireTime?: Timestamp;
}
/**
 * 优惠券信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.CouponInfo
 */
export interface CouponInfo {
    /**
     * 提示框信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.CouponToast toast = 1;
     */
    toast?: CouponToast;
    /**
     * 弹窗信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PopWin pop_win = 2;
     */
    popWin?: PopWin;
}
/**
 * 优惠券提示框文案信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.CouponTextInfo
 */
export interface CouponTextInfo {
    /**
     * 提示框文案-播正片6分钟预览
     *
     * @generated from protobuf field: string positive_preview = 1;
     */
    positivePreview: string;
    /**
     * 提示框文案-播非正片分节ep
     *
     * @generated from protobuf field: string section = 2;
     */
    section: string;
}
/**
 * 优惠券提示框信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.CouponToast
 */
export interface CouponToast {
    /**
     * 提示框文案信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.CouponTextInfo text_info = 1;
     */
    textInfo?: CouponTextInfo;
    /**
     * 提示框按钮
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ButtonInfo button = 2;
     */
    button?: ButtonInfo;
}
/**
 * dash条目
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.DashItem
 */
export interface DashItem {
    /**
     * 清晰度
     *
     * @generated from protobuf field: uint32 id = 1;
     */
    id: number;
    /**
     * 主线流
     *
     * @generated from protobuf field: string base_url = 2;
     */
    baseUrl: string;
    /**
     * 备用流
     *
     * @generated from protobuf field: repeated string backup_url = 3;
     */
    backupUrl: string[];
    /**
     * 带宽
     *
     * @generated from protobuf field: uint32 bandwidth = 4;
     */
    bandwidth: number;
    /**
     * 编码id
     *
     * @generated from protobuf field: uint32 codecid = 5;
     */
    codecid: number;
    /**
     * md5
     *
     * @generated from protobuf field: string md5 = 6;
     */
    md5: string;
    /**
     * 视频大小
     *
     * @generated from protobuf field: uint64 size = 7;
     */
    size: bigint;
    /**
     * 帧率
     *
     * @generated from protobuf field: string frame_rate = 8;
     */
    frameRate: string;
}
/**
 * dash视频流
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.DashVideo
 */
export interface DashVideo {
    /**
     * 主线流
     *
     * @generated from protobuf field: string base_url = 1;
     */
    baseUrl: string;
    /**
     * 备用流
     *
     * @generated from protobuf field: repeated string backup_url = 2;
     */
    backupUrl: string[];
    /**
     * 带宽
     *
     * @generated from protobuf field: uint32 bandwidth = 3;
     */
    bandwidth: number;
    /**
     * 编码id
     *
     * @generated from protobuf field: uint32 codecid = 4;
     */
    codecid: number;
    /**
     * md5
     *
     * @generated from protobuf field: string md5 = 5;
     */
    md5: string;
    /**
     * 大小
     *
     * @generated from protobuf field: uint64 size = 6;
     */
    size: bigint;
    /**
     * 伴音质量id
     *
     * @generated from protobuf field: uint32 audio_id = 7;
     */
    audioId: number;
    /**
     * 是否非全二压
     *
     * @generated from protobuf field: bool no_rexcode = 8;
     */
    noRexcode: boolean;
    /**
     * 帧率
     *
     * @generated from protobuf field: string frame_rate = 9;
     */
    frameRate: string;
    /**
     * 宽
     *
     * @generated from protobuf field: int32 width = 10;
     */
    width: number;
    /**
     * 高
     *
     * @generated from protobuf field: int32 height = 11;
     */
    height: number;
}
/**
 * 鉴权浮层
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Dialog
 */
export interface Dialog {
    /**
     * 鉴权限制码
     *
     * @generated from protobuf field: int64 code = 1;
     */
    code: bigint;
    /**
     * 鉴权限制信息
     *
     * @generated from protobuf field: string msg = 2;
     */
    msg: string;
    /**
     * 浮层类型
     *
     * @generated from protobuf field: string type = 3;
     */
    type: string;
    /**
     * 浮层样式类型
     *
     * @generated from protobuf field: string style_type = 4;
     */
    styleType: string;
    /**
     * 浮层配置
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.DialogConfig config = 5;
     */
    config?: DialogConfig;
    /**
     * 标题
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo title = 6;
     */
    title?: TextInfo;
    /**
     * 副标题
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo subtitle = 7;
     */
    subtitle?: TextInfo;
    /**
     * 图片信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ImageInfo image = 8;
     */
    image?: ImageInfo;
    /**
     * 按钮列表
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.ButtonInfo button = 9;
     */
    button: ButtonInfo[];
    /**
     * 底部描述
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ButtonInfo bottom_desc = 10;
     */
    bottomDesc?: ButtonInfo;
    /**
     * 埋点上报信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Report report = 11;
     */
    report?: Report;
    /**
     * 倒计时 秒
     *
     * @generated from protobuf field: int32 count_down_sec = 12;
     */
    countDownSec: number;
    /**
     * 右下描述
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo right_bottom_desc = 13;
     */
    rightBottomDesc?: TextInfo;
    /**
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.BottomDisplay bottom_display = 14;
     */
    bottomDisplay: BottomDisplay[];
}
/**
 * 鉴权浮层配置
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.DialogConfig
 */
export interface DialogConfig {
    /**
     * 是否显示高斯模糊背景图
     *
     * @generated from protobuf field: bool is_show_cover = 1;
     */
    isShowCover: boolean;
    /**
     * 是否响应转屏
     *
     * @generated from protobuf field: bool is_orientation_enable = 2;
     */
    isOrientationEnable: boolean;
    /**
     * 是否响应上滑吸顶
     *
     * @generated from protobuf field: bool is_nested_scroll_enable = 3;
     */
    isNestedScrollEnable: boolean;
    /**
     * 是否强制竖屏
     *
     * @generated from protobuf field: bool is_force_halfscreen_enable = 4;
     */
    isForceHalfscreenEnable: boolean;
}
/**
 * 当前分辨率信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Dimension
 */
export interface Dimension {
    /**
     * 宽
     *
     * @generated from protobuf field: int32 width = 1;
     */
    width: number;
    /**
     * 长
     *
     * @generated from protobuf field: int32 height = 2;
     */
    height: number;
    /**
     * 旋转角度
     *
     * @generated from protobuf field: int32 rotate = 3;
     */
    rotate: number;
}
/**
 * 杜比音频信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.DolbyItem
 */
export interface DolbyItem {
    /**
     * 杜比类型
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.DolbyItem.Type type = 1;
     */
    type: DolbyItem_Type;
    /**
     * 音频流
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.DashItem audio = 2;
     */
    audio?: DashItem;
}
/**
 * 杜比类型
 *
 * @generated from protobuf enum bilibili.pgc.gateway.player.v2.DolbyItem.Type
 */
export declare enum DolbyItem_Type {
    /**
     * NONE
     *
     * @generated from protobuf enum value: NONE = 0;
     */
    NONE = 0,
    /**
     * 普通杜比音效
     *
     * @generated from protobuf enum value: COMMON = 1;
     */
    COMMON = 1,
    /**
     * 全景杜比音效
     *
     * @generated from protobuf enum value: ATMOS = 2;
     */
    ATMOS = 2
}
/**
 * 播放结束页
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.EndPage
 */
export interface EndPage {
    /**
     * 鉴权浮层
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Dialog dialog = 1;
     */
    dialog?: Dialog;
    /**
     * 播放完后是否隐藏end_page
     *
     * @generated from protobuf field: bool hide = 2;
     */
    hide: boolean;
}
/**
 * 事件
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Event
 */
export interface Event {
    /**
     * 震动
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Shake shake = 1;
     */
    shake?: Shake;
}
/**
 * ? 放映室提示语
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.FreyaConfig
 */
export interface FreyaConfig {
    /**
     * @generated from protobuf field: string desc = 1;
     */
    desc: string;
    /**
     * @generated from protobuf field: int32 type = 2;
     */
    type: number;
    /**
     * @generated from protobuf field: int32 issued_cnt = 3;
     */
    issuedCnt: number;
    /**
     * @generated from protobuf field: bool is_always_show = 4;
     */
    isAlwaysShow: boolean;
    /**
     * @generated from protobuf field: int32 screen_number = 5;
     */
    screenNumber: number;
    /**
     * @generated from protobuf field: int32 full_screen_number = 6;
     */
    fullScreenNumber: number;
}
/**
 * 渐变色信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.GradientColor
 */
export interface GradientColor {
    /**
     * @generated from protobuf field: string start_color = 1;
     */
    startColor: string;
    /**
     * @generated from protobuf field: string end_color = 2;
     */
    endColor: string;
}
/**
 * 高画质试看信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.HighDefinitionTrialInfo
 */
export interface HighDefinitionTrialInfo {
    /**
     * @generated from protobuf field: bool trial_able = 1;
     */
    trialAble: boolean;
    /**
     * @generated from protobuf field: int32 remaining_times = 2;
     */
    remainingTimes: number;
    /**
     * @generated from protobuf field: int32 start = 3;
     */
    start: number;
    /**
     * @generated from protobuf field: int32 time_length = 4;
     */
    timeLength: number;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Toast start_toast = 5;
     */
    startToast?: Toast;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Toast end_toast = 6;
     */
    endToast?: Toast;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Report report = 7;
     */
    report?: Report;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ButtonInfo quality_open_tip_btn = 8;
     */
    qualityOpenTipBtn?: ButtonInfo;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ButtonInfo no_longer_trial_btn = 9;
     */
    noLongerTrialBtn?: ButtonInfo;
}
/**
 * 图片信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.ImageInfo
 */
export interface ImageInfo {
    /**
     * 图片链接
     *
     * @generated from protobuf field: string url = 1;
     */
    url: string;
}
/**
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.MultiView
 */
export interface MultiView {
    /**
     * @generated from protobuf field: string button_material = 1;
     */
    buttonMaterial: string;
    /**
     * @generated from protobuf field: int64 ep_id = 2;
     */
    epId: bigint;
    /**
     * @generated from protobuf field: int64 cid = 3;
     */
    cid: bigint;
    /**
     * @generated from protobuf field: int64 avid = 4;
     */
    avid: bigint;
}
/**
 * 大会员广告: 支付提示信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PayTip
 */
export interface PayTip {
    /**
     * @generated from protobuf field: string title = 1;
     */
    title: string;
    /**
     * @generated from protobuf field: string url = 2;
     */
    url: string;
    /**
     * @generated from protobuf field: string icon = 3;
     */
    icon: string;
    /**
     * @generated from protobuf field: int32 type = 4;
     */
    type: number;
    /**
     * @generated from protobuf field: int32 show_type = 5;
     */
    showType: number;
    /**
     * @generated from protobuf field: string img = 6;
     */
    img: string;
    /**
     * @generated from protobuf field: string bg_day_color = 7;
     */
    bgDayColor: string;
    /**
     * @generated from protobuf field: string bg_night_color = 8;
     */
    bgNightColor: string;
    /**
     * @generated from protobuf field: string bg_line_color = 9;
     */
    bgLineColor: string;
    /**
     * @generated from protobuf field: string bg_night_line_color = 10;
     */
    bgNightLineColor: string;
    /**
     * @generated from protobuf field: string text_color = 11;
     */
    textColor: string;
    /**
     * @generated from protobuf field: string text_night_color = 12;
     */
    textNightColor: string;
    /**
     * @generated from protobuf field: int64 view_start_time = 13;
     */
    viewStartTime: bigint;
    /**
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.ButtonInfo button = 14;
     */
    button: ButtonInfo[];
    /**
     * @generated from protobuf field: int32 url_open_type = 15;
     */
    urlOpenType: number;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Report report = 16;
     */
    report?: Report;
    /**
     * @generated from protobuf field: int32 angle_style = 17;
     */
    angleStyle: number;
    /**
     * @generated from protobuf field: int32 report_type = 18;
     */
    reportType: number;
    /**
     * @generated from protobuf field: map<string, string> order_report_params = 19;
     */
    orderReportParams: {
        [key: string]: string;
    };
}
/**
 * 禁用功能配置
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PlayAbilityConf
 */
export interface PlayAbilityConf {
    /**
     * @generated from protobuf field: bool background_play_disable = 1;
     */
    backgroundPlayDisable: boolean;
    /**
     * @generated from protobuf field: bool flip_disable = 2;
     */
    flipDisable: boolean;
    /**
     * @generated from protobuf field: bool cast_disable = 3;
     */
    castDisable: boolean;
    /**
     * @generated from protobuf field: bool feedback_disable = 4;
     */
    feedbackDisable: boolean;
    /**
     * @generated from protobuf field: bool subtitle_disable = 5;
     */
    subtitleDisable: boolean;
    /**
     * @generated from protobuf field: bool playback_rate_disable = 6;
     */
    playbackRateDisable: boolean;
    /**
     * @generated from protobuf field: bool time_up_disable = 7;
     */
    timeUpDisable: boolean;
    /**
     * @generated from protobuf field: bool playback_mode_disable = 8;
     */
    playbackModeDisable: boolean;
    /**
     * @generated from protobuf field: bool scale_mode_disable = 9;
     */
    scaleModeDisable: boolean;
    /**
     * @generated from protobuf field: bool like_disable = 10;
     */
    likeDisable: boolean;
    /**
     * @generated from protobuf field: bool dislike_disable = 11;
     */
    dislikeDisable: boolean;
    /**
     * @generated from protobuf field: bool coin_disable = 12;
     */
    coinDisable: boolean;
    /**
     * @generated from protobuf field: bool elec_disable = 13;
     */
    elecDisable: boolean;
    /**
     * @generated from protobuf field: bool share_disable = 14;
     */
    shareDisable: boolean;
    /**
     * @generated from protobuf field: bool screen_shot_disable = 15;
     */
    screenShotDisable: boolean;
    /**
     * @generated from protobuf field: bool lock_screen_disable = 16;
     */
    lockScreenDisable: boolean;
    /**
     * @generated from protobuf field: bool recommend_disable = 17;
     */
    recommendDisable: boolean;
    /**
     * @generated from protobuf field: bool playback_speed_disable = 18;
     */
    playbackSpeedDisable: boolean;
    /**
     * @generated from protobuf field: bool definition_disable = 19;
     */
    definitionDisable: boolean;
    /**
     * @generated from protobuf field: bool selections_disable = 20;
     */
    selectionsDisable: boolean;
    /**
     * @generated from protobuf field: bool next_disable = 21;
     */
    nextDisable: boolean;
    /**
     * @generated from protobuf field: bool edit_dm_disable = 22;
     */
    editDmDisable: boolean;
    /**
     * @generated from protobuf field: bool small_window_disable = 23;
     */
    smallWindowDisable: boolean;
    /**
     * @generated from protobuf field: bool shake_disable = 24;
     */
    shakeDisable: boolean;
    /**
     * @generated from protobuf field: bool outer_dm_disable = 25;
     */
    outerDmDisable: boolean;
    /**
     * @generated from protobuf field: bool inner_dm_disable = 26;
     */
    innerDmDisable: boolean;
    /**
     * @generated from protobuf field: bool freya_enter_disable = 27;
     */
    freyaEnterDisable: boolean;
    /**
     * @generated from protobuf field: bool dolby_disable = 28;
     */
    dolbyDisable: boolean;
    /**
     * @generated from protobuf field: bool freya_full_disable = 29;
     */
    freyaFullDisable: boolean;
    /**
     * @generated from protobuf field: bool skip_oped_switch_disable = 30;
     */
    skipOpedSwitchDisable: boolean;
    /**
     * @generated from protobuf field: bool record_screen_disable = 31;
     */
    recordScreenDisable: boolean;
    /**
     * @generated from protobuf field: bool color_optimize_disable = 32;
     */
    colorOptimizeDisable: boolean;
}
/**
 * 云控扩展配置信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PlayAbilityExtConf
 */
export interface PlayAbilityExtConf {
    /**
     * 自定义配置扩展信息
     *
     * @generated from protobuf field: bool allow_close_subtitle = 1;
     */
    allowCloseSubtitle: boolean;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.FreyaConfig freya_config = 2;
     */
    freyaConfig?: FreyaConfig;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.CastTips cast_tips = 3;
     */
    castTips?: CastTips;
}
/**
 * 其他业务信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo
 */
export interface PlayViewBusinessInfo {
    /**
     * 当前视频是否是预览
     *
     * @generated from protobuf field: bool is_preview = 1;
     */
    isPreview: boolean;
    /**
     * 用户是否承包过
     *
     * @generated from protobuf field: bool bp = 2;
     */
    bp: boolean;
    /**
     * drm使用
     *
     * @generated from protobuf field: string marlin_token = 3;
     */
    marlinToken: string;
    /**
     * 倍速动效色值
     *
     * @generated from protobuf field: string playback_speed_color = 4;
     */
    playbackSpeedColor: string;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ContinuePlayInfo continue_play_info = 5;
     */
    continuePlayInfo?: ContinuePlayInfo;
    /**
     * 跳过片头/片尾配置
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.ClipInfo clip_info = 6;
     */
    clipInfo: ClipInfo[];
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.InlineType inline_type = 7;
     */
    inlineType: InlineType;
    /**
     * @generated from protobuf field: int32 ep_whole_duration = 8;
     */
    epWholeDuration: number;
    /**
     * 当前分辨率信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Dimension dimension = 9;
     */
    dimension?: Dimension;
    /**
     * @generated from protobuf field: map<int32, bilibili.pgc.gateway.player.v2.QualityExtInfo> quality_ext_map = 10;
     */
    qualityExtMap: {
        [key: number]: QualityExtInfo;
    };
    /**
     * @generated from protobuf field: map<string, int32> exp_map = 11;
     */
    expMap: {
        [key: string]: number;
    };
    /**
     * DRM技术类型
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.DrmTechType drm_tech_type = 12;
     */
    drmTechType: DrmTechType;
}
/**
 * 播放页信息-响应
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PlayViewReply
 */
export interface PlayViewReply {
    /**
     * 视频流信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.VideoInfo video_info = 1;
     */
    videoInfo?: VideoInfo;
    /**
     * 播放控件用户自定义配置
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PlayAbilityConf play_conf = 2;
     */
    playConf?: PlayAbilityConf;
    /**
     * 业务需要的其他信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo business = 3;
     */
    business?: PlayViewBusinessInfo;
    /**
     * 事件
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Event event = 4;
     */
    event?: Event;
    /**
     * 展示信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ViewInfo view_info = 5;
     */
    viewInfo?: ViewInfo;
    /**
     * 自定义配置扩展信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PlayAbilityExtConf play_ext_conf = 6;
     */
    playExtConf?: PlayAbilityExtConf;
}
/**
 * 播放页信息-请求
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PlayViewReq
 */
export interface PlayViewReq {
    /**
     * 剧集epid
     *
     * @generated from protobuf field: int64 epid = 1 [jstype = JS_STRING];
     */
    epid: string;
    /**
     * 视频cid
     *
     * @generated from protobuf field: int64 cid = 2 [jstype = JS_STRING];
     */
    cid: string;
    /**
     * 清晰度
     *
     * @generated from protobuf field: int64 qn = 3 [jstype = JS_NUMBER];
     */
    qn: number;
    /**
     * 视频流版本
     *
     * @generated from protobuf field: int32 fnver = 4;
     */
    fnver: number;
    /**
     * 视频流格式
     *
     * @generated from protobuf field: int32 fnval = 5;
     */
    fnval: number;
    /**
     * 下载模式
     * 0:播放 1:flv下载 2:dash下载
     *
     * @generated from protobuf field: uint32 download = 6;
     */
    download: number;
    /**
     * 流url强制是用域名
     * 0:允许使用ip 1:使用http 2:使用https
     *
     * @generated from protobuf field: int32 force_host = 7;
     */
    forceHost: number;
    /**
     * 是否4K
     *
     * @generated from protobuf field: bool fourk = 8;
     */
    fourk: boolean;
    /**
     * 当前页spm
     *
     * @generated from protobuf field: string spmid = 9;
     */
    spmid: string;
    /**
     * 上一页spm
     *
     * @generated from protobuf field: string from_spmid = 10;
     */
    fromSpmid: string;
    /**
     * 青少年模式
     *
     * @generated from protobuf field: int32 teenagers_mode = 11;
     */
    teenagersMode: number;
    /**
     * 视频编码
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.CodeType prefer_codec_type = 12;
     */
    preferCodecType: CodeType;
    /**
     * 是否强制请求预览视频
     *
     * @generated from protobuf field: bool is_preview = 13;
     */
    isPreview: boolean;
    /**
     * 一起看房间id
     *
     * @generated from protobuf field: int64 room_id = 14 [jstype = JS_NUMBER];
     */
    roomId: number;
    /**
     * 是否需要展示信息
     *
     * @generated from protobuf field: bool is_need_view_info = 15;
     */
    isNeedViewInfo: boolean;
    /**
     * 场景控制
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.SceneControl scene_control = 16;
     */
    sceneControl?: SceneControl;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.InlineScene inline_scene = 17;
     */
    inlineScene: InlineScene;
    /**
     * @generated from protobuf field: int64 material_no = 18 [jstype = JS_NUMBER];
     */
    materialNo: number;
}
/**
 * 弹窗信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PopWin
 */
export interface PopWin {
    /**
     * 弹窗标题 老字段
     *
     * @generated from protobuf field: string title = 1;
     */
    title: string;
    /**
     * 优惠券列表
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.Coupon coupon = 2;
     */
    coupon: Coupon[];
    /**
     * 弹窗按钮列表
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.ButtonInfo button = 3;
     */
    button: ButtonInfo[];
    /**
     * 底部文案 老字段
     *
     * @generated from protobuf field: string bottom_text = 4;
     */
    bottomText: string;
    /**
     * 弹窗标题 新字段
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo pop_title = 5;
     */
    popTitle?: TextInfo;
    /**
     * 弹窗副标题
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo subtitle = 6;
     */
    subtitle?: TextInfo;
    /**
     * 底部描述 新字段
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ButtonInfo bottom_desc = 7;
     */
    bottomDesc?: ButtonInfo;
    /**
     * 弹窗小图
     *
     * @generated from protobuf field: string cover = 8;
     */
    cover: string;
    /**
     * 弹窗类型
     *
     * @generated from protobuf field: string pop_type = 9;
     */
    popType: string;
}
/**
 * 广告组件: 竖屏时视频下部提示栏
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.PromptBar
 */
export interface PromptBar {
    /**
     * 主标题, 如: "本片含大会员专享内容"
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo title = 1;
     */
    title?: TextInfo;
    /**
     * 副标题, 如: "成为大会员可免费看全部剧集"
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo sub_title = 2;
     */
    subTitle?: TextInfo;
    /**
     * 副标题前面的icon
     *
     * @generated from protobuf field: string sub_title_icon = 3;
     */
    subTitleIcon: string;
    /**
     * 背景图
     *
     * @generated from protobuf field: string bg_image = 4;
     */
    bgImage: string;
    /**
     * 背景渐变色
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.GradientColor bg_gradient_color = 5;
     */
    bgGradientColor?: GradientColor;
    /**
     * 按钮
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.ButtonInfo button = 6;
     */
    button: ButtonInfo[];
    /**
     * 埋点上报信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Report report = 7;
     */
    report?: Report;
    /**
     * @generated from protobuf field: string full_screen_ip_icon = 8;
     */
    fullScreenIpIcon: string;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.GradientColor full_screen_bg_gradient_color = 9;
     */
    fullScreenBgGradientColor?: GradientColor;
}
/**
 * 云控拓展视频画质信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.QualityExtInfo
 */
export interface QualityExtInfo {
    /**
     * 是否支持试看
     *
     * @generated from protobuf field: bool trial_support = 1;
     */
    trialSupport: boolean;
}
/**
 * 埋点上报信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Report
 */
export interface Report {
    /**
     * 曝光事件
     *
     * @generated from protobuf field: string show_event_id = 1;
     */
    showEventId: string;
    /**
     * 点击事件
     *
     * @generated from protobuf field: string click_event_id = 2;
     */
    clickEventId: string;
    /**
     * 埋点透传参数
     *
     * @generated from protobuf field: string extends = 3;
     */
    extends: string;
}
/**
 * 分段流条目
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.ResponseUrl
 */
export interface ResponseUrl {
    /**
     * 分段序号
     *
     * @generated from protobuf field: uint32 order = 1;
     */
    order: number;
    /**
     * 分段时长
     *
     * @generated from protobuf field: uint64 length = 2;
     */
    length: bigint;
    /**
     * 分段大小
     *
     * @generated from protobuf field: uint64 size = 3;
     */
    size: bigint;
    /**
     * 主线流
     *
     * @generated from protobuf field: string url = 4;
     */
    url: string;
    /**
     * 备用流
     *
     * @generated from protobuf field: repeated string backup_url = 5;
     */
    backupUrl: string[];
    /**
     * md5
     *
     * @generated from protobuf field: string md5 = 6;
     */
    md5: string;
}
/**
 * 场景控制
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.SceneControl
 */
export interface SceneControl {
    /**
     * 是否收藏播单
     *
     * @generated from protobuf field: bool fav_playlist = 1;
     */
    favPlaylist: boolean;
    /**
     * 是否小窗
     *
     * @generated from protobuf field: bool small_window = 2;
     */
    smallWindow: boolean;
    /**
     * 是否画中画
     *
     * @generated from protobuf field: bool pip = 3;
     */
    pip: boolean;
    /**
     * @generated from protobuf field: bool was_he_inline = 4;
     */
    wasHeInline: boolean;
    /**
     * @generated from protobuf field: bool is_need_trial = 5;
     */
    isNeedTrial: boolean;
}
/**
 * 分段视频流
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.SegmentVideo
 */
export interface SegmentVideo {
    /**
     * 分段视频流列表
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.ResponseUrl segment = 1;
     */
    segment: ResponseUrl[];
}
/**
 * 震动
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Shake
 */
export interface Shake {
    /**
     * 文件地址
     *
     * @generated from protobuf field: string file = 1;
     */
    file: string;
}
/**
 * 视频流信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Stream
 */
export interface Stream {
    /**
     * 元数据
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.StreamInfo info = 1;
     */
    info?: StreamInfo;
    /**
     * @generated from protobuf oneof: content
     */
    content: {
        oneofKind: "dashVideo";
        /**
         * dash流
         *
         * @generated from protobuf field: bilibili.pgc.gateway.player.v2.DashVideo dash_video = 2;
         */
        dashVideo: DashVideo;
    } | {
        oneofKind: "segmentVideo";
        /**
         * 分段流
         *
         * @generated from protobuf field: bilibili.pgc.gateway.player.v2.SegmentVideo segment_video = 3;
         */
        segmentVideo: SegmentVideo;
    } | {
        oneofKind: undefined;
    };
}
/**
 * 流媒体元数据
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.StreamInfo
 */
export interface StreamInfo {
    /**
     * 清晰度
     *
     * @generated from protobuf field: uint32 quality = 1;
     */
    quality: number;
    /**
     * 格式
     *
     * @generated from protobuf field: string format = 2;
     */
    format: string;
    /**
     * 格式描述
     *
     * @generated from protobuf field: string description = 3;
     */
    description: string;
    /**
     * 错误码
     *
     * @generated from protobuf field: uint32 err_code = 4;
     */
    errCode: number;
    /**
     * 不满足条件信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.StreamLimit limit = 5;
     */
    limit?: StreamLimit;
    /**
     * 是否需要vip
     *
     * @generated from protobuf field: bool need_vip = 6;
     */
    needVip: boolean;
    /**
     * 是否需要登录
     *
     * @generated from protobuf field: bool need_login = 7;
     */
    needLogin: boolean;
    /**
     * 是否完整
     *
     * @generated from protobuf field: bool intact = 8;
     */
    intact: boolean;
    /**
     * 是否非全二压
     *
     * @generated from protobuf field: bool no_rexcode = 9;
     */
    noRexcode: boolean;
    /**
     * 清晰度属性位
     *
     * @generated from protobuf field: int64 attribute = 10;
     */
    attribute: bigint;
    /**
     * 新版格式描述
     *
     * @generated from protobuf field: string new_description = 11;
     */
    newDescription: string;
    /**
     * 格式文字
     *
     * @generated from protobuf field: string display_desc = 12;
     */
    displayDesc: string;
    /**
     * 新版格式描述备注
     *
     * @generated from protobuf field: string superscript = 13;
     */
    superscript: string;
}
/**
 * 清晰度不满足条件信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.StreamLimit
 */
export interface StreamLimit {
    /**
     * 标题
     *
     * @generated from protobuf field: string title = 1;
     */
    title: string;
    /**
     * 跳转地址
     *
     * @generated from protobuf field: string uri = 2;
     */
    uri: string;
    /**
     * 提示信息
     *
     * @generated from protobuf field: string msg = 3;
     */
    msg: string;
}
/**
 * 文案信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.TextInfo
 */
export interface TextInfo {
    /**
     * 文案
     *
     * @generated from protobuf field: string text = 1;
     */
    text: string;
    /**
     * 字体色值
     *
     * @generated from protobuf field: string textColor = 2;
     */
    textColor: string;
    /**
     * 字体色值-夜间模式
     *
     * @generated from protobuf field: string textColorNight = 3;
     */
    textColorNight: string;
}
/**
 * toast
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.Toast
 */
export interface Toast {
    /**
     * toast文案 老字段
     *
     * @generated from protobuf field: string text = 1;
     */
    text: string;
    /**
     * toast按钮
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.ButtonInfo button = 2;
     */
    button?: ButtonInfo;
    /**
     * 显示样式类型
     *
     * @generated from protobuf field: int32 show_style_type = 3;
     */
    showStyleType: number;
    /**
     * 图标
     *
     * @generated from protobuf field: string icon = 4;
     */
    icon: string;
    /**
     * toast文案 新字段
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.TextInfo toast_text = 5;
     */
    toastText?: TextInfo;
    /**
     * 埋点上报信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Report report = 6;
     */
    report?: Report;
    /**
     * @generated from protobuf field: map<string, string> order_report_params = 7;
     */
    orderReportParams: {
        [key: string]: string;
    };
}
/**
 * 视频url信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.VideoInfo
 */
export interface VideoInfo {
    /**
     * 视频清晰度
     *
     * @generated from protobuf field: uint32 quality = 1;
     */
    quality: number;
    /**
     * 视频格式
     *
     * @generated from protobuf field: string format = 2;
     */
    format: string;
    /**
     * 视频时长
     *
     * @generated from protobuf field: uint64 timelength = 3;
     */
    timelength: bigint;
    /**
     * 视频编码id
     *
     * @generated from protobuf field: uint32 video_codecid = 4;
     */
    videoCodecid: number;
    /**
     * 视频流
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.Stream stream_list = 5;
     */
    streamList: Stream[];
    /**
     * 伴音流
     *
     * @generated from protobuf field: repeated bilibili.pgc.gateway.player.v2.DashItem dash_audio = 6;
     */
    dashAudio: DashItem[];
    /**
     * 杜比伴音流
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.DolbyItem dolby = 7;
     */
    dolby?: DolbyItem;
}
/**
 * 展示信息
 *
 * @generated from protobuf message bilibili.pgc.gateway.player.v2.ViewInfo
 */
export interface ViewInfo {
    /**
     * 鉴权浮层
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Dialog dialog = 1;
     */
    dialog?: Dialog;
    /**
     * toast
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.Toast toast = 2;
     */
    toast?: Toast;
    /**
     * 优惠券信息
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.CouponInfo coupon_info = 3;
     */
    couponInfo?: CouponInfo;
    /**
     * 未购买的超前点播ep列表
     *
     * @generated from protobuf field: repeated int64 demand_no_pay_epids = 4;
     */
    demandNoPayEpids: bigint[];
    /**
     * 播放结束页
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.EndPage end_page = 5;
     */
    endPage?: EndPage;
    /**
     * @generated from protobuf field: map<string, bool> exp_config = 6;
     */
    expConfig: {
        [key: string]: boolean;
    };
    /**
     * 弹窗
     *
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PopWin pop_win = 7;
     */
    popWin?: PopWin;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PromptBar try_watch_prompt_bar = 8;
     */
    tryWatchPromptBar?: PromptBar;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.PayTip pay_tip = 9;
     */
    payTip?: PayTip;
    /**
     * @generated from protobuf field: bilibili.pgc.gateway.player.v2.HighDefinitionTrialInfo high_definition_trial_info = 10;
     */
    highDefinitionTrialInfo?: HighDefinitionTrialInfo;
    /**
     * @generated from protobuf field: map<string, bilibili.pgc.gateway.player.v2.Dialog> ext_dialog = 11;
     */
    extDialog: {
        [key: string]: Dialog;
    };
}
/**
 * 跳过片头/片尾配置: Clip类型
 *
 * @generated from protobuf enum bilibili.pgc.gateway.player.v2.ClipType
 */
export declare enum ClipType {
    /**
     * @generated from protobuf enum value: NT_UNKNOWN = 0;
     */
    NT_UNKNOWN = 0,
    /**
     * 跳过OP
     *
     * @generated from protobuf enum value: CLIP_TYPE_OP = 1;
     */
    CLIP_TYPE_OP = 1,
    /**
     * 跳过ED
     *
     * @generated from protobuf enum value: CLIP_TYPE_ED = 2;
     */
    CLIP_TYPE_ED = 2,
    /**
     * @generated from protobuf enum value: CLIP_TYPE_HE = 3;
     */
    CLIP_TYPE_HE = 3,
    /**
     * @generated from protobuf enum value: CLIP_TYPE_MULTI_VIEW = 4;
     */
    CLIP_TYPE_MULTI_VIEW = 4
}
/**
 * 编码类型
 *
 * @generated from protobuf enum bilibili.pgc.gateway.player.v2.CodeType
 */
export declare enum CodeType {
    /**
     * 默认
     *
     * @generated from protobuf enum value: NOCODE = 0;
     */
    NOCODE = 0,
    /**
     * H.264
     *
     * @generated from protobuf enum value: CODE264 = 1;
     */
    CODE264 = 1,
    /**
     * H.265
     *
     * @generated from protobuf enum value: CODE265 = 2;
     */
    CODE265 = 2
}
/**
 * DRM技术类型
 *
 * @generated from protobuf enum bilibili.pgc.gateway.player.v2.DrmTechType
 */
export declare enum DrmTechType {
    /**
     * @generated from protobuf enum value: NON = 0;
     */
    NON = 0,
    /**
     * @generated from protobuf enum value: FAIR_PLAY = 1;
     */
    FAIR_PLAY = 1
}
/**
 * @generated from protobuf enum bilibili.pgc.gateway.player.v2.InlineScene
 */
export declare enum InlineScene {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: RELATED_EP = 1;
     */
    RELATED_EP = 1,
    /**
     * @generated from protobuf enum value: HE = 2;
     */
    HE = 2,
    /**
     * @generated from protobuf enum value: SKIP = 3;
     */
    SKIP = 3
}
/**
 * @generated from protobuf enum bilibili.pgc.gateway.player.v2.InlineType
 */
export declare enum InlineType {
    /**
     * @generated from protobuf enum value: TYPE_UNKNOWN = 0;
     */
    TYPE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: TYPE_WHOLE = 1;
     */
    TYPE_WHOLE = 1,
    /**
     * @generated from protobuf enum value: TYPE_HE_CLIP = 2;
     */
    TYPE_HE_CLIP = 2,
    /**
     * @generated from protobuf enum value: TYPE_PREVIEW = 3;
     */
    TYPE_PREVIEW = 3
}
/**
 * 错误码
 *
 * @generated from protobuf enum bilibili.pgc.gateway.player.v2.PlayErr
 */
export declare enum PlayErr {
    /**
     * @generated from protobuf enum value: NoErr = 0;
     */
    NoErr = 0,
    /**
     * 管控类型的错误码
     *
     * @generated from protobuf enum value: WithMultiDeviceLoginErr = 1;
     */
    WithMultiDeviceLoginErr = 1
}
declare class BadgeInfo$Type extends MessageType<BadgeInfo> {
    constructor();
    create(value?: PartialMessage<BadgeInfo>): BadgeInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BadgeInfo): BadgeInfo;
    internalBinaryWrite(message: BadgeInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.BadgeInfo
 */
export declare const BadgeInfo: BadgeInfo$Type;
declare class BottomDisplay$Type extends MessageType<BottomDisplay> {
    constructor();
    create(value?: PartialMessage<BottomDisplay>): BottomDisplay;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BottomDisplay): BottomDisplay;
    internalBinaryWrite(message: BottomDisplay, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.BottomDisplay
 */
export declare const BottomDisplay: BottomDisplay$Type;
declare class ButtonInfo$Type extends MessageType<ButtonInfo> {
    constructor();
    create(value?: PartialMessage<ButtonInfo>): ButtonInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ButtonInfo): ButtonInfo;
    private binaryReadMap15;
    internalBinaryWrite(message: ButtonInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.ButtonInfo
 */
export declare const ButtonInfo: ButtonInfo$Type;
declare class CastTips$Type extends MessageType<CastTips> {
    constructor();
    create(value?: PartialMessage<CastTips>): CastTips;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CastTips): CastTips;
    internalBinaryWrite(message: CastTips, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.CastTips
 */
export declare const CastTips: CastTips$Type;
declare class ClipInfo$Type extends MessageType<ClipInfo> {
    constructor();
    create(value?: PartialMessage<ClipInfo>): ClipInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ClipInfo): ClipInfo;
    internalBinaryWrite(message: ClipInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.ClipInfo
 */
export declare const ClipInfo: ClipInfo$Type;
declare class ContinuePlayInfo$Type extends MessageType<ContinuePlayInfo> {
    constructor();
    create(value?: PartialMessage<ContinuePlayInfo>): ContinuePlayInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ContinuePlayInfo): ContinuePlayInfo;
    internalBinaryWrite(message: ContinuePlayInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.ContinuePlayInfo
 */
export declare const ContinuePlayInfo: ContinuePlayInfo$Type;
declare class Coupon$Type extends MessageType<Coupon> {
    constructor();
    create(value?: PartialMessage<Coupon>): Coupon;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Coupon): Coupon;
    internalBinaryWrite(message: Coupon, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Coupon
 */
export declare const Coupon: Coupon$Type;
declare class CouponInfo$Type extends MessageType<CouponInfo> {
    constructor();
    create(value?: PartialMessage<CouponInfo>): CouponInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CouponInfo): CouponInfo;
    internalBinaryWrite(message: CouponInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.CouponInfo
 */
export declare const CouponInfo: CouponInfo$Type;
declare class CouponTextInfo$Type extends MessageType<CouponTextInfo> {
    constructor();
    create(value?: PartialMessage<CouponTextInfo>): CouponTextInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CouponTextInfo): CouponTextInfo;
    internalBinaryWrite(message: CouponTextInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.CouponTextInfo
 */
export declare const CouponTextInfo: CouponTextInfo$Type;
declare class CouponToast$Type extends MessageType<CouponToast> {
    constructor();
    create(value?: PartialMessage<CouponToast>): CouponToast;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CouponToast): CouponToast;
    internalBinaryWrite(message: CouponToast, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.CouponToast
 */
export declare const CouponToast: CouponToast$Type;
declare class DashItem$Type extends MessageType<DashItem> {
    constructor();
    create(value?: PartialMessage<DashItem>): DashItem;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DashItem): DashItem;
    internalBinaryWrite(message: DashItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.DashItem
 */
export declare const DashItem: DashItem$Type;
declare class DashVideo$Type extends MessageType<DashVideo> {
    constructor();
    create(value?: PartialMessage<DashVideo>): DashVideo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DashVideo): DashVideo;
    internalBinaryWrite(message: DashVideo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.DashVideo
 */
export declare const DashVideo: DashVideo$Type;
declare class Dialog$Type extends MessageType<Dialog> {
    constructor();
    create(value?: PartialMessage<Dialog>): Dialog;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Dialog): Dialog;
    internalBinaryWrite(message: Dialog, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Dialog
 */
export declare const Dialog: Dialog$Type;
declare class DialogConfig$Type extends MessageType<DialogConfig> {
    constructor();
    create(value?: PartialMessage<DialogConfig>): DialogConfig;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DialogConfig): DialogConfig;
    internalBinaryWrite(message: DialogConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.DialogConfig
 */
export declare const DialogConfig: DialogConfig$Type;
declare class Dimension$Type extends MessageType<Dimension> {
    constructor();
    create(value?: PartialMessage<Dimension>): Dimension;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Dimension): Dimension;
    internalBinaryWrite(message: Dimension, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Dimension
 */
export declare const Dimension: Dimension$Type;
declare class DolbyItem$Type extends MessageType<DolbyItem> {
    constructor();
    create(value?: PartialMessage<DolbyItem>): DolbyItem;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DolbyItem): DolbyItem;
    internalBinaryWrite(message: DolbyItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.DolbyItem
 */
export declare const DolbyItem: DolbyItem$Type;
declare class EndPage$Type extends MessageType<EndPage> {
    constructor();
    create(value?: PartialMessage<EndPage>): EndPage;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EndPage): EndPage;
    internalBinaryWrite(message: EndPage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.EndPage
 */
export declare const EndPage: EndPage$Type;
declare class Event$Type extends MessageType<Event> {
    constructor();
    create(value?: PartialMessage<Event>): Event;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Event): Event;
    internalBinaryWrite(message: Event, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Event
 */
export declare const Event: Event$Type;
declare class FreyaConfig$Type extends MessageType<FreyaConfig> {
    constructor();
    create(value?: PartialMessage<FreyaConfig>): FreyaConfig;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FreyaConfig): FreyaConfig;
    internalBinaryWrite(message: FreyaConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.FreyaConfig
 */
export declare const FreyaConfig: FreyaConfig$Type;
declare class GradientColor$Type extends MessageType<GradientColor> {
    constructor();
    create(value?: PartialMessage<GradientColor>): GradientColor;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GradientColor): GradientColor;
    internalBinaryWrite(message: GradientColor, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.GradientColor
 */
export declare const GradientColor: GradientColor$Type;
declare class HighDefinitionTrialInfo$Type extends MessageType<HighDefinitionTrialInfo> {
    constructor();
    create(value?: PartialMessage<HighDefinitionTrialInfo>): HighDefinitionTrialInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: HighDefinitionTrialInfo): HighDefinitionTrialInfo;
    internalBinaryWrite(message: HighDefinitionTrialInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.HighDefinitionTrialInfo
 */
export declare const HighDefinitionTrialInfo: HighDefinitionTrialInfo$Type;
declare class ImageInfo$Type extends MessageType<ImageInfo> {
    constructor();
    create(value?: PartialMessage<ImageInfo>): ImageInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ImageInfo): ImageInfo;
    internalBinaryWrite(message: ImageInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.ImageInfo
 */
export declare const ImageInfo: ImageInfo$Type;
declare class MultiView$Type extends MessageType<MultiView> {
    constructor();
    create(value?: PartialMessage<MultiView>): MultiView;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MultiView): MultiView;
    internalBinaryWrite(message: MultiView, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.MultiView
 */
export declare const MultiView: MultiView$Type;
declare class PayTip$Type extends MessageType<PayTip> {
    constructor();
    create(value?: PartialMessage<PayTip>): PayTip;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PayTip): PayTip;
    private binaryReadMap19;
    internalBinaryWrite(message: PayTip, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PayTip
 */
export declare const PayTip: PayTip$Type;
declare class PlayAbilityConf$Type extends MessageType<PlayAbilityConf> {
    constructor();
    create(value?: PartialMessage<PlayAbilityConf>): PlayAbilityConf;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayAbilityConf): PlayAbilityConf;
    internalBinaryWrite(message: PlayAbilityConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PlayAbilityConf
 */
export declare const PlayAbilityConf: PlayAbilityConf$Type;
declare class PlayAbilityExtConf$Type extends MessageType<PlayAbilityExtConf> {
    constructor();
    create(value?: PartialMessage<PlayAbilityExtConf>): PlayAbilityExtConf;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayAbilityExtConf): PlayAbilityExtConf;
    internalBinaryWrite(message: PlayAbilityExtConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PlayAbilityExtConf
 */
export declare const PlayAbilityExtConf: PlayAbilityExtConf$Type;
declare class PlayViewBusinessInfo$Type extends MessageType<PlayViewBusinessInfo> {
    constructor();
    create(value?: PartialMessage<PlayViewBusinessInfo>): PlayViewBusinessInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayViewBusinessInfo): PlayViewBusinessInfo;
    private binaryReadMap10;
    private binaryReadMap11;
    internalBinaryWrite(message: PlayViewBusinessInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PlayViewBusinessInfo
 */
export declare const PlayViewBusinessInfo: PlayViewBusinessInfo$Type;
declare class PlayViewReply$Type extends MessageType<PlayViewReply> {
    constructor();
    create(value?: PartialMessage<PlayViewReply>): PlayViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayViewReply): PlayViewReply;
    internalBinaryWrite(message: PlayViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PlayViewReply
 */
export declare const PlayViewReply: PlayViewReply$Type;
declare class PlayViewReq$Type extends MessageType<PlayViewReq> {
    constructor();
    create(value?: PartialMessage<PlayViewReq>): PlayViewReq;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayViewReq): PlayViewReq;
    internalBinaryWrite(message: PlayViewReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PlayViewReq
 */
export declare const PlayViewReq: PlayViewReq$Type;
declare class PopWin$Type extends MessageType<PopWin> {
    constructor();
    create(value?: PartialMessage<PopWin>): PopWin;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PopWin): PopWin;
    internalBinaryWrite(message: PopWin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PopWin
 */
export declare const PopWin: PopWin$Type;
declare class PromptBar$Type extends MessageType<PromptBar> {
    constructor();
    create(value?: PartialMessage<PromptBar>): PromptBar;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PromptBar): PromptBar;
    internalBinaryWrite(message: PromptBar, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.PromptBar
 */
export declare const PromptBar: PromptBar$Type;
declare class QualityExtInfo$Type extends MessageType<QualityExtInfo> {
    constructor();
    create(value?: PartialMessage<QualityExtInfo>): QualityExtInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: QualityExtInfo): QualityExtInfo;
    internalBinaryWrite(message: QualityExtInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.QualityExtInfo
 */
export declare const QualityExtInfo: QualityExtInfo$Type;
declare class Report$Type extends MessageType<Report> {
    constructor();
    create(value?: PartialMessage<Report>): Report;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Report): Report;
    internalBinaryWrite(message: Report, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Report
 */
export declare const Report: Report$Type;
declare class ResponseUrl$Type extends MessageType<ResponseUrl> {
    constructor();
    create(value?: PartialMessage<ResponseUrl>): ResponseUrl;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ResponseUrl): ResponseUrl;
    internalBinaryWrite(message: ResponseUrl, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.ResponseUrl
 */
export declare const ResponseUrl: ResponseUrl$Type;
declare class SceneControl$Type extends MessageType<SceneControl> {
    constructor();
    create(value?: PartialMessage<SceneControl>): SceneControl;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SceneControl): SceneControl;
    internalBinaryWrite(message: SceneControl, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.SceneControl
 */
export declare const SceneControl: SceneControl$Type;
declare class SegmentVideo$Type extends MessageType<SegmentVideo> {
    constructor();
    create(value?: PartialMessage<SegmentVideo>): SegmentVideo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SegmentVideo): SegmentVideo;
    internalBinaryWrite(message: SegmentVideo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.SegmentVideo
 */
export declare const SegmentVideo: SegmentVideo$Type;
declare class Shake$Type extends MessageType<Shake> {
    constructor();
    create(value?: PartialMessage<Shake>): Shake;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Shake): Shake;
    internalBinaryWrite(message: Shake, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Shake
 */
export declare const Shake: Shake$Type;
declare class Stream$Type extends MessageType<Stream> {
    constructor();
    create(value?: PartialMessage<Stream>): Stream;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Stream): Stream;
    internalBinaryWrite(message: Stream, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Stream
 */
export declare const Stream: Stream$Type;
declare class StreamInfo$Type extends MessageType<StreamInfo> {
    constructor();
    create(value?: PartialMessage<StreamInfo>): StreamInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamInfo): StreamInfo;
    internalBinaryWrite(message: StreamInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.StreamInfo
 */
export declare const StreamInfo: StreamInfo$Type;
declare class StreamLimit$Type extends MessageType<StreamLimit> {
    constructor();
    create(value?: PartialMessage<StreamLimit>): StreamLimit;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamLimit): StreamLimit;
    internalBinaryWrite(message: StreamLimit, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.StreamLimit
 */
export declare const StreamLimit: StreamLimit$Type;
declare class TextInfo$Type extends MessageType<TextInfo> {
    constructor();
    create(value?: PartialMessage<TextInfo>): TextInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TextInfo): TextInfo;
    internalBinaryWrite(message: TextInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.TextInfo
 */
export declare const TextInfo: TextInfo$Type;
declare class Toast$Type extends MessageType<Toast> {
    constructor();
    create(value?: PartialMessage<Toast>): Toast;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Toast): Toast;
    private binaryReadMap7;
    internalBinaryWrite(message: Toast, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.Toast
 */
export declare const Toast: Toast$Type;
declare class VideoInfo$Type extends MessageType<VideoInfo> {
    constructor();
    create(value?: PartialMessage<VideoInfo>): VideoInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: VideoInfo): VideoInfo;
    internalBinaryWrite(message: VideoInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.VideoInfo
 */
export declare const VideoInfo: VideoInfo$Type;
declare class ViewInfo$Type extends MessageType<ViewInfo> {
    constructor();
    create(value?: PartialMessage<ViewInfo>): ViewInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewInfo): ViewInfo;
    private binaryReadMap6;
    private binaryReadMap11;
    internalBinaryWrite(message: ViewInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.pgc.gateway.player.v2.ViewInfo
 */
export declare const ViewInfo: ViewInfo$Type;
/**
 * @generated ServiceType for protobuf service bilibili.pgc.gateway.player.v2.PlayURL
 */
export declare const PlayURL: any;
export {};
