// @generated by protobuf-ts 2.8.2 with parameter output_javascript
// @generated from protobuf file "bilibili/polymer/app/search/v1/search.proto" (package "bilibili.polymer.app.search.v1", syntax proto3)
// tslint:disable
import { Search } from "./search";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service bilibili.polymer.app.search.v1.Search
 */
export class SearchClient {
    constructor(_transport) {
        this._transport = _transport;
        this.typeName = Search.typeName;
        this.methods = Search.methods;
        this.options = Search.options;
    }
    /**
     * 搜索所有类型结果
     *
     * @generated from protobuf rpc: SearchAll(bilibili.polymer.app.search.v1.SearchAllRequest) returns (bilibili.polymer.app.search.v1.SearchAllResponse);
     */
    searchAll(input, options) {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * 搜索指定类型结果
     *
     * @generated from protobuf rpc: SearchByType(bilibili.polymer.app.search.v1.SearchByTypeRequest) returns (bilibili.polymer.app.search.v1.SearchByTypeResponse);
     */
    searchByType(input, options) {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SearchComic(bilibili.polymer.app.search.v1.SearchComicRequest) returns (bilibili.polymer.app.search.v1.SearchComicResponse);
     */
    searchComic(input, options) {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
}
